# Generated by Django 4.2.3 on 2023-10-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Apple', 'Apple'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Asus', 'Asus'), ('Acer', 'Acer')], default='Apple', max_length=100)),
                ('issue_year', models.IntegerField()),
                ('ram', models.CharField(max_length=10)),
                ('hdd', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('qty', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
