# Generated by Django 4.2.3 on 2023-10-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_notebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=256)),
                ('author_name', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('published', 'Published'), ('unpublished', 'Unpublished'), ('banned', 'Banned')], default='unpublished', max_length=20)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('publication_date', models.DateTimeField()),
                ('category', models.CharField(choices=[('general', 'general'), ('programming', 'programming'), ('sport', 'sport'), ('food', 'food')], default='general', max_length=50)),
            ],
        ),
    ]
